set_property IOSTANDARD LVDS_25 [get_ports Sys_clk_P]
set_property PACKAGE_PIN L5 [get_ports Sys_clk_P]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SEN]
set_property PACKAGE_PIN V13 [get_ports ADC1_SEN]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SDATA]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_OVR]
set_property IOSTANDARD LVDS_25 [get_ports ADC1_CLK_P]
set_property PACKAGE_PIN U14 [get_ports ADC1_SDATA]
set_property PACKAGE_PIN U13 [get_ports ADC1_SCLK]
set_property PACKAGE_PIN V16 [get_ports ADC1_OVR]
set_property PACKAGE_PIN K4 [get_ports ADC1_CLK_P]
set_property IOSTANDARD LVCMOS33 [get_ports ADC1_ADS5547_reset]
set_property PACKAGE_PIN W16 [get_ports ADC1_ADS5547_reset]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC1_DATA_P[0]}]
set_property PACKAGE_PIN N6 [get_ports {ADC1_DATA_P[6]}]
set_property PACKAGE_PIN M4 [get_ports {ADC1_DATA_P[5]}]
set_property PACKAGE_PIN K7 [get_ports {ADC1_DATA_P[4]}]
set_property PACKAGE_PIN L2 [get_ports {ADC1_DATA_P[3]}]
set_property PACKAGE_PIN J5 [get_ports {ADC1_DATA_P[2]}]
set_property PACKAGE_PIN J7 [get_ports {ADC1_DATA_P[1]}]
set_property PACKAGE_PIN J8 [get_ports {ADC1_DATA_P[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ps_emio_tri_io[0]}]
set_property PACKAGE_PIN Y12 [get_ports {ps_emio_tri_io[3]}]
set_property PACKAGE_PIN Y13 [get_ports {ps_emio_tri_io[2]}]
set_property PACKAGE_PIN V11 [get_ports {ps_emio_tri_io[1]}]
set_property PACKAGE_PIN W11 [get_ports {ps_emio_tri_io[0]}]



set_property PACKAGE_PIN P6 [get_ports In_Trig_P]
set_property IOSTANDARD LVDS_25 [get_ports In_Trig_P]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200M]
